trigger:
- main
- rel/*

pr:
- main
- rel/*

stages:
- stage: Build
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        Channel_Zip:
          ReleaseChannel: Zip
        Channel_Store:
          ReleaseChannel: Store
        Channel_Nightly:
          ReleaseChannel: Nightly
        Channel_Choco:
          ReleaseChannel: Choco
        Channel_WebAssembly:
          ReleaseChannel: WebAssembly
        Channel_UnoSkia:
          ReleaseChannel: UnoSkia

    steps:
        
    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        version: 8.x

    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . nbgv
      displayName: Install NBGV tool

    - script: nbgv cloud -c -a
      displayName: Set Version

    - powershell: |
        mkdir $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)

        # Set versions

        # Update appxmanifests. These must be done before build.
        [xml]$manifest = Get-Content ".\PackageExplorer.Package\package.appxmanifest"
        $manifest.Package.Identity.Version = "$(GitBuildVersionSimple).0"
        $manifest.Save(".\PackageExplorer.Package\package.appxmanifest")

        [xml]$manifest = Get-Content ".\PackageExplorer.Package\Package-Nightly.appxmanifest"
        $manifest.Package.Identity.Version = "$(GitBuildVersionSimple).0"
        $manifest.Save(".\PackageExplorer.Package\Package-Nightly.appxmanifest")

        # Update badges
        [xml]$badge = Get-Content ".\Build\ci_badge.svg"
        $badge.svg.g[1].text[2].InnerText = "$(GitBuildVersionSimple).0"
        $badge.svg.g[1].text[3].InnerText = "$(GitBuildVersionSimple).0"
        $badge.Save("$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\ci_badge.svg")

        [xml]$badge = Get-Content ".\Build\store_badge.svg"
        $badge.svg.g[1].text[2].InnerText = "$(GitBuildVersionSimple).0"
        $badge.svg.g[1].text[3].InnerText = "$(GitBuildVersionSimple).0"
        $badge.Save("$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\stable_badge.svg")
      displayName: Update manifest and badge versions

    - powershell: |
        # Update App Insights key
        [xml]$doc = Get-Content ".\PackageExplorer\ApplicationInsights.config"
        $doc.ApplicationInsights.ConnectionString = "$(AppInsightsKey)"
        $doc.Save(".\PackageExplorer\ApplicationInsights.config")

      displayName: Set AppInsights Config
      env:
        AppInsightsKey: $(AppInsightsKey)
      condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['AppInsightsKey'], '')))

    - task: MSBuild@1
      displayName: Build Package
      inputs:
        solution: PackageExplorer.Package/PackageExplorer.Package.wapproj
        msbuildArguments: /restore /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\\" /bl:$(Build.ArtifactStagingDirectory)\Logs\$(ReleaseChannel).binlog
        configuration: $(BuildConfiguration)
        maximumCpuCount: true
      condition: and(succeeded(), or(eq(variables['ReleaseChannel'], 'Nightly'), eq(variables['ReleaseChannel'], 'Store')))

    - task: DotNetCoreCLI@2
      displayName: Build for Zip and Choco
      inputs:
        command: publish
        projects: 'PackageExplorer/NuGetPackageExplorer.csproj'
        arguments: -c $(BuildConfiguration) /p:PublishProfile=Properties/PublishProfiles/WinX64.pubxml /bl:$(Build.ArtifactStagingDirectory)\Logs\$(ReleaseChannel).binlog
        zipAfterPublish: false
        modifyOutputPath: false
        publishWebProjects: false
      condition: and(succeeded(), or(eq(variables['ReleaseChannel'], 'Zip'), eq(variables['ReleaseChannel'], 'Choco')))

    - task: DotNetCoreCLI@2
      displayName: Pack Libraries as Package
      inputs:
        command: pack
        arguments: /bl:$(Build.ArtifactStagingDirectory)\Logs\Libraries.binlog
        packagesToPack: '**/*.csproj;!**/NuGetPackageExplorer.csproj'
        configuration: $(BuildConfiguration)
        packDirectory: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\NuGet
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Zip'))

    - powershell: |
        # Chocolatey
        & choco.exe pack .\PackageExplorer\NuGetPackageExplorer.nuspec --version $(NBGV_ChocolateyPackageVersion) --OutputDirectory $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
      displayName: Create Choco package
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Choco'))

    - task: ArchiveFiles@1
      displayName: Zip Windows PackageExplorer files
      inputs:
        archiveType: zip
        rootFolder: PackageExplorer/bin/$(BuildConfiguration)/net8.0-windows10.0.22000/win-x64/publish
        archiveFile: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\PackageExplorer.$(Build.BuildNumber).zip
        includeRootFolder: false
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Zip'))

    - task: MSBuild@1
      displayName: Build Uno Apps
      inputs:
        solution: $(build.sourcesdirectory)/NuGetPackageExplorer-uno.slnf
        msbuildArguments: /r /p:Configuration=Release /p:UNO_BUILD_ONLY=true /p:NpeAiInstrumentationKey=$(AppInsightsKeyWebAssembly) /bl:$(Build.ArtifactStagingDirectory)\Logs\$(ReleaseChannel).binlog
        maximumCpuCount: true
      condition: and(succeeded(), or(eq(variables['ReleaseChannel'], 'Nightly'), eq(variables['ReleaseChannel'], 'WebAssembly'), eq(variables['ReleaseChannel'], 'UnoSkia')))

    - task: ArchiveFiles@1
      displayName: Zip Gtk PackageExplorer files
      inputs:
        archiveType: zip
        rootFolder: $(build.sourcesdirectory)/Uno/NuGetPackageExplorer.Skia.Gtk/bin/Release/net8.0
        archiveFile: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\PackageExplorer.Skia.Gtk.$(Build.BuildNumber).zip
        includeRootFolder: false
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'UnoSkia'))

    - task: CopyFiles@2
      displayName: Copy WebAssembly Package
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/Uno/NuGetPackageExplorer.Wasm/bin/Release/net8.0/dist'
        Contents: '**'
        TargetFolder: $(build.artifactstagingdirectory)\$(ReleaseChannel)
        CleanTargetFolder: false
        OverWrite: false
        flattenFolders: false
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'WebAssembly'))

    - publish: '$(build.sourcesdirectory)/Uno/Api'
      displayName: Publish Cors bypass Azure Function
      artifact: CorsAzureFunction
      condition: and(succeeded(), eq(variables['ReleaseChannel'], 'WebAssembly'))

    - publish: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
      displayName: Publish Build Packages
      artifact: $(ReleaseChannel)
  
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)\Logs
        artifactName: Logs    
      displayName: Publish Build Logs      
      condition: always()

    - publish: Build
      displayName: Publish signing scripts
      artifact: SigningScripts

- stage: CodeSign
  dependsOn: Build
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - job: CodeSign
    displayName: Code Signing
    pool:
      vmImage: windows-latest
    variables:
    - group: SignCLI Config
  
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download Zip Artifacts
      inputs:
        artifactName: Zip
        targetPath: $(Pipeline.Workspace)/ToSign/Zip

    - task: DownloadPipelineArtifact@2
      displayName: Download Choco Artifacts
      inputs:
        artifactName: Choco
        targetPath: $(Pipeline.Workspace)/ToSign/Choco

    - task: DownloadPipelineArtifact@2
      displayName: Download Nightly Artifacts
      inputs:
        artifactName: Nightly
        targetPath: $(Pipeline.Workspace)/ToSign/Nightly

    - download: current
      artifact: SigningScripts

    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        version: 8.x

    # Install the code signing tool
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . --prerelease sign 
      displayName: Install SignTool tool

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure RM (NPE)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          .\sign code azure-key-vault `
          "**/*.{appxbundle,msixbundle,appinstaller,zip,nupkg}" `
          --base-directory "$(Pipeline.Workspace)\ToSign" `
          --file-list "$(Pipeline.Workspace)\SigningScripts\filelist.txt" `
          --publisher-name "NuGet Package Explorer" `
          --description "NuGet Package Explorer" `
          --description-url "https://github.com/NuGetPackageExplorer/NuGetPackageExplorer" `
          --azure-key-vault-managed-identity `
          --azure-key-vault-certificate "$(SignKeyVaultCertificate)" `
          --azure-key-vault-url "$(SignKeyVaultUrl)"
      displayName: Authenticode Sign artifacts

    - publish: $(Pipeline.Workspace)/ToSign/Zip
      displayName: Publish Signed Zip Packages
      artifact: ZipSigned

    - publish: $(Pipeline.Workspace)/ToSign/Choco
      displayName: Publish Signed Choco Packages
      artifact: ChocoSigned

    - publish: $(Pipeline.Workspace)/ToSign/Nightly
      displayName: Publish Signed Choco Packages
      artifact: NightlySigned

